services:

  mysql:
    image: mysql:8.0
    container_name: poll-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poll_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    image: nilesh0203/poll-backend:latest
    container_name: poll-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/poll_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: nilesh0203/poll-frontend:latest
    container_name: poll-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data: