services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pollapp

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    image: nilesh0203/poll-backend:latest
    container_name: backend
    restart: always

    depends_on:
      mysql-db:
        condition: service_healthy

    environment:
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_NAME: pollapp
      DB_USER: root
      DB_PASS: root

    ports:
      - "8081:8081"


  frontend:
    image: nilesh0203/poll-frontend:latest
    container_name: frontend
    restart: always

    depends_on:
      - backend

    ports:
      - "80:80"


volumes:
  mysql-data: